services:
  db:
    image: mysql:8.0
    container_name: safeview-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-safeview}
      MYSQL_USER: ${DB_USER:-safeview}
      MYSQL_PASSWORD: ${DB_PASSWORD:-safeview}
      TZ: Asia/Seoul
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    command:
      [
        "mysqld",
        "--default-authentication-plugin=mysql_native_password",
        "--default-time-zone=+09:00",
      ]
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-p${DB_PASSWORD:-root}",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    container_name: safeview-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: Asia/Seoul
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${DB_NAME:-safeview}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-safeview}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-safeview}
      JWT_SECRET: ${JWT_SECRET}
      AI_SERVER_URL: http://camera-ai:8000
      AI_SERVER_API_KEY: ${AI_SERVER_API_KEY}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_HOST: ${EMAIL_HOST}
      JAVA_OPTS: "-XX:+UseG1GC -XX:MaxRAMPercentage=75.0 -Duser.timezone=Asia/Seoul"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_REGION: ${S3_REGION}
    ports:
      - "8080:8080"
    networks:
      - default

  camera-ai:
    build:
      context: ./services/camera-ai
      dockerfile: Dockerfile
    container_name: safeview-camera-ai
    depends_on:
      backend:
        condition: service_started
    environment:
      TZ: Asia/Seoul
      BACKEND_API_URL: http://backend:8080
      SPRING_MAKE_ENTITY_URL: http://backend:8080/api/videos/make-entity
      API_HOST: 0.0.0.0
      API_PORT: 8000
      AI_API_KEY: ${AI_SERVER_API_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_REGION: ${S3_REGION}
    ports:
      - "8000:8000"
    volumes:
      - camera_uploads:/app/uploads
      - camera_api_results:/app/api_results

  frontend:
    build:
      context: ./services/frontend
    container_name: safeview-frontend
    depends_on:
      - backend
      - camera-ai
    environment:
      TZ: Asia/Seoul
    ports:
      - "5173:80"

volumes:
  db_data:
  camera_uploads:
  camera_api_results:

networks:
  default:
    name: safeview-net
